
import { Language } from './types';

export const STRINGS = {
  [Language.AR]: {
    appName: 'TalibSpace',
    welcome: 'مرحبا بيك فـ فضاء طلبة CMC',
    languageRoom: 'غرفة اللغات',
    practice: 'مارس اللغة مع خوتك',
    wordOfDay: 'كلمة اليوم',
    startQuiz: 'بدا الكويز',
    partnerMatch: 'شريك عشوائي',
    pointsAwarded: 'زتي نقط في اللغة!',
    raiseHand: 'هز يدك',
    correctMe: 'صحح ليا',
    login: 'دخول',
    signup: 'تسجيل',
    studentOnly: 'هاد الفضاء حصري لطلبة CMC فقط',
    feed: 'الرئيسية',
    resources: 'دروس',
    opportunities: 'فرص',
    random: 'تواصل عشوائي',
    profile: 'بروفايل',
    announcements: 'إعلانات',
    activities: 'أنشطة',
    messages: 'رسائل',
    groups: 'مجموعات',
    live: 'مباشر',
    aiAssistant: 'مساعد AI',
    friends: 'الأصدقاء',
    friendRequests: 'طلبات الصداقة',
    addFriend: 'إضافة صديق',
    accept: 'قبل',
    decline: 'رفض',
    suggested: 'مقترحين ليك',
    noRequests: 'ما عندك حتى طلب جديد',
    postSomething: 'شارك شي حاجة مع خوتك...',
    post: 'نشر',
    like: 'عجبني',
    comment: 'تعليق',
    logout: 'خروج',
    searching: 'كنقلبو ليك على شي حد...',
    startCall: 'بدا مكالمة عشوائية',
    skip: 'التالي',
    end: 'قطع',
    report: 'تبليغ',
    matched: 'لقينا ليك واحد الطالب من CMC!',
    safetyNotice: 'هاد الفضاء آمن، أي تصرف غير لائق كيعرضك للطرد النهائي.',
    internships: 'تدريبات',
    jobs: 'فرص عمل',
    urgent: 'عاجل',
    trips: 'رحلات',
    sports: 'رياضة',
    join: 'شارك',
    joined: 'مشارك',
    allFilieres: 'جميع التخصصات',
    call: 'اتصال',
    videoCall: 'مكالمة فيديو',
    audioCall: 'مكالمة صوتية',
    joinCall: 'دخول للمكالمة',
    ongoingCall: 'مكالمة جارية...',
    points: 'نقطة',
    level: 'المستوى',
    premiumUnlock: 'فتح المميزات الممتازة',
    premiumActive: 'الاشتراك الممتاز نشط',
    subscribeTooltip: 'اشترك لفتح ميزات حصرية',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    yearly: 'سنوي',
    premiumFeatures: [
      'وصول لغرف اللغات الخاصة',
      'زيادة نقاط XP',
      'تطابقات عشوائية أسرع',
      'شارات حصرية للملف الشخصي'
    ]
  },
  [Language.FR]: {
    appName: 'TalibSpace',
    welcome: 'Bienvenue sur TalibSpace CMC',
    languageRoom: 'Language Room',
    practice: 'Pratiquez avec vos pairs',
    wordOfDay: 'Mot du Jour',
    startQuiz: 'Démarrer le Quiz',
    partnerMatch: 'Partenaire Aléatoire',
    pointsAwarded: 'Points XP gagnés !',
    raiseHand: 'Lever la main',
    correctMe: 'Corrige-moi',
    login: 'Connexion',
    signup: 'Inscription',
    studentOnly: 'Espace exclusif aux étudiants CMC',
    feed: 'Accueil',
    resources: 'Cours',
    opportunities: 'Opportunités',
    random: 'Connect',
    profile: 'Profil',
    announcements: 'Annonces',
    activities: 'Activités',
    messages: 'Messages',
    groups: 'Groupes',
    live: 'En Direct',
    aiAssistant: 'Assistant AI',
    friends: 'Amis',
    friendRequests: 'Demandes',
    addFriend: 'Ajouter',
    accept: 'Accepter',
    decline: 'Refuser',
    suggested: 'Suggestions',
    noRequests: 'Aucune demande',
    postSomething: 'Partagez avec vos collègues...',
    post: 'Publier',
    like: "J'aime",
    comment: 'Commenter',
    logout: 'Déconnexion',
    searching: 'Recherche d\'un partenaire...',
    startCall: 'Lancer un appel aléatoire',
    skip: 'Suivant',
    end: 'Terminer',
    report: 'Signaler',
    matched: 'Vous avez été matché avec un étudiant !',
    safetyNotice: 'Espace sécurisé. Tout comportement inapproprié entraîne un ban.',
    internships: 'Stages',
    jobs: 'Emplois',
    urgent: 'Urgent',
    trips: 'Voyages',
    sports: 'Sports',
    join: 'Rejoindre',
    joined: 'Inscrit',
    allFilieres: 'Toutes les filières',
    call: 'Appeler',
    videoCall: 'Appel Vidéo',
    audioCall: 'Appel Audio',
    joinCall: 'Rejoindre l\'appel',
    ongoingCall: 'Appel en cours...',
    points: 'Points',
    level: 'Niveau',
    premiumUnlock: 'Débloquer le Premium',
    premiumActive: 'Premium Actif',
    subscribeTooltip: 'Abonnez-vous pour débloquer les fonctionnalités exclusives',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    premiumFeatures: [
      'Accès aux salons de langue exclusifs',
      'Boost de points XP',
      'Matchs aléatoires prioritaires',
      'Badges de profil exclusifs'
    ]
  },
  [Language.EN]: {
    appName: 'TalibSpace',
    welcome: 'Welcome to TalibSpace CMC',
    languageRoom: 'Language Room',
    practice: 'Practice with the squad',
    wordOfDay: 'Word of the Day',
    startQuiz: 'Start Quiz',
    partnerMatch: 'Random Partner',
    pointsAwarded: 'XP Points Awarded!',
    raiseHand: 'Raise Hand',
    correctMe: 'Correct Me',
    login: 'Login',
    signup: 'Sign Up',
    studentOnly: 'Exclusive for CMC Students only',
    feed: 'Home',
    resources: 'Courses',
    opportunities: 'Opportunities',
    random: 'Random Connect',
    profile: 'Profile',
    announcements: 'Announcements',
    activities: 'Activities',
    messages: 'Messages',
    groups: 'Groups',
    live: 'Live Events',
    aiAssistant: 'AI Buddy',
    friends: 'Friends',
    friendRequests: 'Requests',
    addFriend: 'Add Friend',
    accept: 'Accept',
    decline: 'Decline',
    suggested: 'Suggested',
    noRequests: 'No pending requests',
    postSomething: 'Share something with the squad...',
    post: 'Post',
    like: 'Like',
    comment: 'Comment',
    logout: 'Logout',
    searching: 'Searching for a match...',
    startCall: 'Start Random Call',
    skip: 'Skip',
    end: 'End',
    report: 'Report',
    matched: 'Found a CMC Student!',
    safetyNotice: 'Safe space. Inappropriate behavior results in a permanent ban.',
    internships: 'Internships',
    jobs: 'Jobs',
    urgent: 'Urgent',
    trips: 'Trips',
    sports: 'Sports',
    join: 'Join',
    joined: 'Joined',
    allFilieres: 'All Specialties',
    call: 'Call',
    videoCall: 'Video Call',
    audioCall: 'Audio Call',
    joinCall: 'Join Call',
    ongoingCall: 'Ongoing Call...',
    points: 'Points',
    level: 'Level',
    premiumUnlock: 'Unlock Premium',
    premiumActive: 'Premium Active',
    subscribeTooltip: 'Subscribe to unlock exclusive features',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    premiumFeatures: [
      'Access to specialized language rooms',
      'XP point boosts',
      'Priority random matching',
      'Exclusive profile badges'
    ]
  }
};

export const LANGUAGE_ROOMS = [
  { id: 'en', name: 'English Room', icon: '🇬🇧', students: 42, level: 'Advanced', type: 'Public Room', bg: 'from-blue-600/10 to-indigo-600/10' },
  { id: 'fr', name: 'French Room', icon: '🇫🇷', students: 28, level: 'Intermediate', type: 'Public Room', bg: 'from-blue-400/10 to-red-400/10' },
  { id: 'es', name: 'Spanish Room', icon: '🇪🇸', students: 12, level: 'Beginner', type: 'Public Room', bg: 'from-yellow-400/10 to-red-500/10' },
  { id: 'de', name: 'German Room', icon: '🇩🇪', students: 8, level: 'Advanced', type: 'Public Room', bg: 'from-zinc-400/10 to-yellow-600/10' },
];

export const PREMIUM_ROOMS = [
  { id: 'speak', name: 'Speaking Practice', icon: '🎤', students: 15, level: 'B2+', type: 'Voice Only', desc: 'No text allowed. Just pure oral practice and peer-to-peer feedback.', active: true, premium: true },
  { id: 'debate', name: 'Debate Club', icon: '🎥', students: 6, level: 'C1', type: 'Video Enabled', desc: 'Structured arguments and high-level vocabulary practice.', active: true, premium: true },
  { id: 'study', name: 'Study Session', icon: '📚', students: 24, level: 'All', type: 'Silent/Chat', desc: 'Focus with lo-fi beats and peer support via text.', active: true, premium: true },
];

export const MOCK_QUIZ = {
  en: [
    { id: 'q1', question: 'Which word describes a very successful person in their field?', options: ['Maverick', 'Amateur', 'Pioneer', 'Intern'], correctIndex: 2, explanation: 'A pioneer is someone who is among the first to explore or settle a new country or area or develop a new method.' },
  ],
  fr: [
    { id: 'q1', question: 'Comment dit-on "Internship" en Français?', options: ['Travail', 'Stage', 'Apprentissage', 'Vacances'], correctIndex: 1, explanation: 'Un stage est une période de pratique en entreprise.' },
  ],
  es: [
    { id: 'q1', question: '¿Cómo se dice "Friend" en español?', options: ['Amigo', 'Enemigo', 'Hermano', 'Padre'], correctIndex: 0, explanation: 'Amigo es la palabra estándar para friend.' },
  ],
  de: [
     { id: 'q1', question: 'Wie sagt man "Thank you" auf Deutsch?', options: ['Bitte', 'Danke', 'Guten Tag', 'Hallo'], correctIndex: 1, explanation: 'Danke ist das deutsche Wort für thank you.' },
  ]
};

export const WORD_OF_THE_DAY = {
  en: { word: 'Resilient', translation: 'صامد / مرن', example: 'Students are resilient despite the exam stress.' },
  fr: { word: 'Épanouissement', translation: 'ازدهار / تفتح', example: 'Le sport contribue à l\'épanouissement personnel.' },
  es: { word: 'Entusiasmo', translation: 'حماس', example: 'Tiene mucho entusiasmo por aprender.' },
  de: { word: 'Leidenschaft', translation: 'شغف', example: 'Musik ist meine Leidenschaft.' },
};

export const MOCK_POSTS = [
  {
    id: '1',
    authorId: 'u1',
    authorName: 'Mehdi Bennani',
    authorAvatar: 'https://i.pravatar.cc/150?u=mehdi',
    content: 'Drari, shkun 3endo résumé dyal Python? 🐍 Imtihan 9reb!',
    timestamp: '2h ago',
    likes: 12,
    comments: [],
    type: 'question'
  },
  {
    id: '2',
    authorId: 'u2',
    authorName: 'Salma El Amrani',
    authorAvatar: 'https://i.pravatar.cc/150?u=salma',
    content: 'Huge internship opportunity in Casablanca at OCP. Check the resources tab! 🚀',
    timestamp: '5h ago',
    likes: 24,
    comments: [],
    type: 'advice'
  }
];

export const MOCK_ANNOUNCEMENTS = [
  { id: 'a1', title: 'Exam Schedule Update', content: 'Python exam moved to next Monday 9:00 AM.', type: 'urgent', filiere: 'Digital', date: 'Today' },
  { id: 'a2', title: 'Cybersecurity Seminar', content: 'OCP experts visiting campus tomorrow at 2PM.', type: 'event', filiere: 'All', date: 'Tomorrow' },
];

export const MOCK_ACTIVITIES = [
  { id: 'act1', title: 'Trip to Ifrane', description: 'Weekend rihla! Skiing and chilling. Limited spots. 🏔️', type: 'Trip', date: 'Feb 20', location: 'Ifrane', participants: 35, maxParticipants: 50, isJoined: false },
  { id: 'act2', title: 'Football Tournament', description: 'Inter-filière cup. Who wins the trophy? 🏆', type: 'Sport', date: 'Feb 15', location: 'Campus Field', participants: 80, maxParticipants: 100, isJoined: true },
];

export const MOCK_RESOURCES = [
  { id: 'r1', title: 'Python Basics 2024', description: 'Full guide for beginners and intermediates.', specialty: 'Digital', fileType: 'PDF', sharedBy: 'Mehdi', downloads: 145 },
  { id: 'r2', title: 'Industrial Automation', description: 'Diagnostic techniques for Siemens PLCs.', specialty: 'Industrie', fileType: 'DOCX', sharedBy: 'Anas', downloads: 89 },
];

export const MOCK_LIVE_EVENTS = [
  { id: 'l1', title: 'How to Land an Internship', host: 'Prof. Alami', viewers: 124, thumbnail: 'https://picsum.photos/seed/live1/400/225', isLive: true },
  { id: 'l2', title: 'UI/UX Design Workshop', host: 'Salma El Amrani', viewers: 45, thumbnail: 'https://picsum.photos/seed/live2/400/225', isLive: true },
];

export const MOCK_CHATS = [
  { id: 'c1', partnerName: 'Yassine', partnerAvatar: 'https://i.pravatar.cc/150?u=yass', lastMessage: 'Shof hadak l-lien dyal Python.', unread: true },
  { id: 'c2', partnerName: 'Kanza', partnerAvatar: 'https://i.pravatar.cc/150?u=kanz', lastMessage: 'Thank you for the notes!', unread: false },
];
